// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU7m9P-kj9_tN4CZuQ5Sega7hTAZZ5hsQ',
    appId: '1:85178257984:web:7fb9e79b5506e5cc1405a5',
    messagingSenderId: '85178257984',
    projectId: 'mycomm-d242a',
    authDomain: 'mycomm-d242a.firebaseapp.com',
    storageBucket: 'mycomm-d242a.appspot.com',
    measurementId: 'G-P10XQX9FMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGC7mz7KehYtbdKY9iuU_KrPQgzuEgCGY',
    appId: '1:85178257984:android:b537c891449423081405a5',
    messagingSenderId: '85178257984',
    projectId: 'mycomm-d242a',
    storageBucket: 'mycomm-d242a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatqtLOYOCnvspQPozjGFmFaopsAcaE1I',
    appId: '1:85178257984:ios:a29dfaf0c0b5ad471405a5',
    messagingSenderId: '85178257984',
    projectId: 'mycomm-d242a',
    storageBucket: 'mycomm-d242a.appspot.com',
    iosBundleId: 'com.example.myComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAatqtLOYOCnvspQPozjGFmFaopsAcaE1I',
    appId: '1:85178257984:ios:9370ad1d3bfec57e1405a5',
    messagingSenderId: '85178257984',
    projectId: 'mycomm-d242a',
    storageBucket: 'mycomm-d242a.appspot.com',
    iosBundleId: 'com.example.myComm.RunnerTests',
  );
}
